/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;
import java.sql.*;
import ConexaoDB.ModuloConexao;
import Formatacao.FormatTft;
import java.sql.Connection;  
import java.sql.DriverManager;  
import java.sql.SQLException;  
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author adonai
 */
public class Cardapio extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    /**
     * Creates new form Cardapio
     */
    public Cardapio() {
        initComponents();
        txtNome.setDocument(new FormatTft(50, FormatTft.TipoEntrada.NOME));
        conexao = ModuloConexao.conector();
    }
    private void consultar(){
        int busca = jItens.getSelectedIndex();
        if (busca >= 0) {
            String consultaItem = "select * from tbUsuarios where usuario like '" + txtNome.getText() + "%'" + "order by usuario limit " + busca + ",1";
            try {
                conexao = ModuloConexao.conector();
                pst = conexao.prepareStatement(consultaItem);
                rs = pst.executeQuery();
                while (rs.next()) {
                    jItens.setVisible(false);
                    txtId.setText(rs.getString(1));
                    txtNome.setText(rs.getString(2));
                    txtdescriçao.setText(rs.getString(3));
                    txtpreço.setText(rs.getString(4));
                    
                }

            } catch (Exception e) {
            }
        } else {
            jItens.setVisible(false);
        }
    }

    
    private void ajustar(){
        String sql = "update tbCardapio set nomeLanche = ?,descLanche = ?,valorLanche = ? where idLanche = ? ";
       try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNome.getText());
            pst.setString(2, txtdescriçao.getText());
            pst.setString(3, txtpreço.getText());
            pst.setString(4, txtId.getText());
            if (txtNome.getText().isEmpty() || txtdescriçao.getText().isEmpty() || txtpreço.getText().isEmpty() || txtId.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Informe todos os campos");
            } else {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
                txtNome.setText(null);
                txtdescriçao.setText(null);
                txtpreço.setText(null);
                txtId.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel alterar os dados do usuário");
            System.out.println(e);
        } finally {
            try {
                conexao.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JimagemItem = new javax.swing.JLabel();
        Jcardapio = new javax.swing.JLabel();
        Jnome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        Jpreço = new javax.swing.JLabel();
        Jdescriçao = new javax.swing.JLabel();
        txtdescriçao = new javax.swing.JTextField();
        txtpreço = new javax.swing.JTextField();
        Jcodigo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jItens = new javax.swing.JList<>();
        BtAjustar = new javax.swing.JButton();

        JimagemItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Jcardapio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Jcardapio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jcardapio.setText("Cardápio");

        Jnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Jnome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        Jpreço.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Jpreço.setText("Preço:");

        Jdescriçao.setText("Descrição:");

        txtdescriçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescriçaoActionPerformed(evt);
            }
        });

        txtpreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreçoActionPerformed(evt);
            }
        });

        Jcodigo.setText("id:");

        jScrollPane2.setViewportView(jItens);

        BtAjustar.setText("Ajustar");
        BtAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAjustarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Jdescriçao)
                            .addGap(18, 18, 18)
                            .addComponent(txtdescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(JimagemItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(250, 250, 250)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Jpreço)
                        .addGap(37, 37, 37)
                        .addComponent(txtpreço, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Jnome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Jcardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BtAjustar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jcardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JimagemItem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpreço, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jpreço)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jdescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtAjustar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtpreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreçoActionPerformed

    private void txtdescriçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescriçaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescriçaoActionPerformed

    private void BtAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAjustarActionPerformed
        ajustar();
    }//GEN-LAST:event_BtAjustarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAjustar;
    private javax.swing.JLabel Jcardapio;
    private javax.swing.JLabel Jcodigo;
    private javax.swing.JLabel Jdescriçao;
    private javax.swing.JLabel JimagemItem;
    private javax.swing.JLabel Jnome;
    private javax.swing.JLabel Jpreço;
    private javax.swing.JList<String> jItens;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtdescriçao;
    private javax.swing.JTextField txtpreço;
    // End of variables declaration//GEN-END:variables

    private void setDocument(FormatTft formatTft) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
