/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Telas;

import ConexaoDB.ModuloConexao;
import Formatacao.FormatTft;
import java.awt.HeadlessException;
import java.text.NumberFormat;
import java.sql.*;
import javax.swing.JScrollPane;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adonai
 */
public class Pedido extends javax.swing.JInternalFrame{
    

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNomecliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jNomecliente1 = new javax.swing.JLabel();
        jFormattedCep = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxBolo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jComboBoxBolo4 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jComboBoxBolo7 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jComboBoxBolo9 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jComboBoxBolo11 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jComboBoxBolo12 = new javax.swing.JComboBox<>();
        jComboBoxBolo13 = new javax.swing.JComboBox<>();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jComboBoxBolo14 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jComboBoxBolo15 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jComboBoxBolo16 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jComboBoxBolo17 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 214, 53));

        jNomecliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNomecliente.setText("Cep:");
        jPanel1.add(jNomecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        jPanel1.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 380, -1));

        jNomecliente1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNomecliente1.setText("Nome do cliente:");
        jPanel1.add(jNomecliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        try {
            jFormattedCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, -1));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 380, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bairro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cidade:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Número:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 210, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 190, -1));
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Fone:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jComboBoxBolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBoloActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, -1));

        jLabel9.setText("Total a Pagar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 90, -1));

        jLabel11.setText("Bolo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel14.setText("Brownie:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        try {
            jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, -1));

        jComboBoxBolo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, -1));

        jLabel17.setText("Cachorro:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        try {
            jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 90, -1));

        jComboBoxBolo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 50, -1));

        jLabel20.setText("Coxinha:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        try {
            jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 90, -1));

        jComboBoxBolo9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 50, -1));

        jLabel22.setText("Milkshake:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        try {
            jFormattedTextField14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 90, -1));

        jComboBoxBolo11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo11ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 50, -1));

        jLabel23.setText("Pasteis:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        try {
            jFormattedTextField15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 90, -1));

        jComboBoxBolo12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo12ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 50, -1));

        jComboBoxBolo13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo13ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 50, -1));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 90, -1));

        jLabel24.setText("Pizza:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel25.setText("Pudim:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        try {
            jFormattedTextField16.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 90, -1));

        jComboBoxBolo14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo14ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 50, -1));

        jLabel26.setText("Refri:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        try {
            jFormattedTextField17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField17ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 90, -1));

        jComboBoxBolo15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo15ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 50, -1));

        jLabel27.setText("Sanduiche:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        try {
            jFormattedTextField18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField18ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 90, -1));

        jComboBoxBolo16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo16ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 50, -1));

        jLabel28.setText("Suco:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        try {
            jFormattedTextField19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField19ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 90, -1));

        jComboBoxBolo17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBoxBolo17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBolo17ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBolo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
    }//GEN-LAST:event_jList1MouseClicked

    private void jComboBoxBoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBoloActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jComboBoxBolo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo4ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void jComboBoxBolo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo7ActionPerformed

    private void jFormattedTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField12ActionPerformed

    private void jComboBoxBolo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo9ActionPerformed

    private void jFormattedTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField14ActionPerformed

    private void jComboBoxBolo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo11ActionPerformed

    private void jFormattedTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField15ActionPerformed

    private void jComboBoxBolo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo12ActionPerformed

    private void jComboBoxBolo13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo13ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField16ActionPerformed

    private void jComboBoxBolo14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo14ActionPerformed

    private void jFormattedTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField17ActionPerformed

    private void jComboBoxBolo15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo15ActionPerformed

    private void jFormattedTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField18ActionPerformed

    private void jComboBoxBolo16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo16ActionPerformed

    private void jFormattedTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField19ActionPerformed

    private void jComboBoxBolo17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBolo17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBolo17ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxBolo;
    private javax.swing.JComboBox<String> jComboBoxBolo11;
    private javax.swing.JComboBox<String> jComboBoxBolo12;
    private javax.swing.JComboBox<String> jComboBoxBolo13;
    private javax.swing.JComboBox<String> jComboBoxBolo14;
    private javax.swing.JComboBox<String> jComboBoxBolo15;
    private javax.swing.JComboBox<String> jComboBoxBolo16;
    private javax.swing.JComboBox<String> jComboBoxBolo17;
    private javax.swing.JComboBox<String> jComboBoxBolo4;
    private javax.swing.JComboBox<String> jComboBoxBolo7;
    private javax.swing.JComboBox<String> jComboBoxBolo9;
    private javax.swing.JFormattedTextField jFormattedCep;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel jNomecliente;
    private javax.swing.JLabel jNomecliente1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
