package Telas;
import java.sql.*;
import ConexaoDB.ModuloConexao;
import javax.swing.JOptionPane;
/**
 *
 * @author tyago
 */
public class TelaUsuario extends javax.swing.JInternalFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    private void consultar(){
        String sql = "select * from tbUsuarios where idUser = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,txtIdUsuario.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNomeUsuario.setText(rs.getString(2));
                txtFoneUsuario.setText(rs.getString(3));
                txtLoginUsuario.setText(rs.getString(4));
                txtSenhaUsuario.setText(rs.getString(5));
                boxPerfilUsuario.setSelectedItem(rs.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não cadastrado");
                txtNomeUsuario.setText(null);
                txtFoneUsuario.setText(null);
                txtLoginUsuario.setText(null);
                txtSenhaUsuario.setText(null);
                boxPerfilUsuario.setSelectedItem(null);
                        
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void adicionar(){
        String sql = "insert into tbUsuarios(usuario,fone,login,senha,perfil) values(?,?,?,?,?)";
        try {
            conexao = ModuloConexao.conector();
            pst = conexao.prepareStatement(sql);
            //pst.setString(1,txtIdUsuario.getText());
            pst.setString(1,txtNomeUsuario.getText());
            pst.setString(2,txtFoneUsuario.getText());
            pst.setString(3,txtLoginUsuario.getText());
            pst.setString(4,txtSenhaUsuario.getText());
            pst.setString(5,boxPerfilUsuario.getSelectedItem().toString());
            pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso");
                txtIdUsuario.setText(null);
                txtNomeUsuario.setText(null);
                txtFoneUsuario.setText(null);
                txtLoginUsuario.setText(null);
                txtSenhaUsuario.setText(null);
                boxPerfilUsuario.setSelectedItem(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIdUsuario = new javax.swing.JLabel();
        jNomeUsuario = new javax.swing.JLabel();
        jFoneUsuaruo = new javax.swing.JLabel();
        jLoginUsuario = new javax.swing.JLabel();
        jSenhaUsuario = new javax.swing.JLabel();
        jPerfilUsuario = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        txtNomeUsuario = new javax.swing.JTextField();
        txtFoneUsuario = new javax.swing.JTextField();
        txtLoginUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxPerfilUsuario = new javax.swing.JComboBox<>();
        btAdicionar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(640, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jIdUsuario.setText("Id:");
        getContentPane().add(jIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 30, -1, -1));

        jNomeUsuario.setText("Nome:");
        getContentPane().add(jNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 88, -1, -1));

        jFoneUsuaruo.setText("Fone:");
        getContentPane().add(jFoneUsuaruo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 148, -1, -1));

        jLoginUsuario.setText("Login:");
        getContentPane().add(jLoginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 148, -1, -1));

        jSenhaUsuario.setText("Senha:");
        getContentPane().add(jSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 203, -1, 22));

        jPerfilUsuario.setText("Perfil:");
        getContentPane().add(jPerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 206, -1, -1));
        getContentPane().add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 27, 130, -1));

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 85, 447, -1));

        txtFoneUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoneUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtFoneUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 145, 180, -1));
        getContentPane().add(txtLoginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 145, 180, -1));

        txtSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 203, 180, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 322, -1, -1));

        boxPerfilUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));
        boxPerfilUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPerfilUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(boxPerfilUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 203, -1, -1));

        btAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adcionar.png"))); // NOI18N
        btAdicionar.setToolTipText("Adicionar");
        btAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdicionar.setPreferredSize(new java.awt.Dimension(70, 70));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar ");
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setPreferredSize(new java.awt.Dimension(70, 70));
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/atualizar.png"))); // NOI18N
        btAtualizar.setToolTipText("Atualizar");
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAtualizar.setPreferredSize(new java.awt.Dimension(70, 70));
        getContentPane().add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deletar.png"))); // NOI18N
        btDeletar.setToolTipText("Deletar");
        btDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDeletar.setPreferredSize(new java.awt.Dimension(70, 70));
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        setBounds(0, 0, 640, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed

    private void txtFoneUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoneUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoneUsuarioActionPerformed

    private void txtSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUsuarioActionPerformed

    private void boxPerfilUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPerfilUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPerfilUsuarioActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        consultar();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        adicionar();
        
    }//GEN-LAST:event_btAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPerfilUsuario;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jFoneUsuaruo;
    private javax.swing.JLabel jIdUsuario;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLoginUsuario;
    private javax.swing.JLabel jNomeUsuario;
    private javax.swing.JLabel jPerfilUsuario;
    private javax.swing.JLabel jSenhaUsuario;
    private javax.swing.JTextField txtFoneUsuario;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtLoginUsuario;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
